// Code generated by mockery v2.28.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// UrlSaver is an autogenerated mock type for the UrlSaver type
type UrlSaver struct {
	mock.Mock
}

// SaveUrl provides a mock function with given fields: ctx, urlToSave, alias
func (_m *UrlSaver) SaveUrl(ctx context.Context, urlToSave string, alias string) error {
	ret := _m.Called(ctx, urlToSave, alias)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, urlToSave, alias)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewUrlSaver interface {
	mock.TestingT
	Cleanup(func())
}

// NewUrlSaver creates a new instance of UrlSaver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUrlSaver(t mockConstructorTestingTNewUrlSaver) *UrlSaver {
	mock := &UrlSaver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
