// Code generated by mockery v2.28.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// UrlDeleter is an autogenerated mock type for the UrlDeleter type
type UrlDeleter struct {
	mock.Mock
}

// DeleteUrl provides a mock function with given fields: ctx, alias
func (_m *UrlDeleter) DeleteUrl(ctx context.Context, alias string) error {
	ret := _m.Called(ctx, alias)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, alias)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewUrlDeleter interface {
	mock.TestingT
	Cleanup(func())
}

// NewUrlDeleter creates a new instance of UrlDeleter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUrlDeleter(t mockConstructorTestingTNewUrlDeleter) *UrlDeleter {
	mock := &UrlDeleter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
