env: "local"
http_server:
  address: "localhost:8080"
  timeout: 3s
  idle_timeout: 60s
  ctx_timeout: 10s
active_storage: "mongo"
storages:
  sqlite:
    storage_path: "./storage/storage.db"
  mongo:
    uri: "some-mongo-db-uri"
alias_generator:
  address: "http://localhost:8082"
  timeout: 1s
clickhouse:
  dsn: "some-clickhouse-dsn"
  database: "testing"
